// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RescueFlow.Web.Data;

#nullable disable

namespace RescueFlow.Web.Migrations
{
    [DbContext(typeof(RescueFlowDbContext))]
    [Migration("20260522135547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.AlgorithmRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedHospitalsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedVehiclesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredVehiclesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RescueCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedHospitalId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedVehiclesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("int");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValidationPassed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AlgorithmRunLogs");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RescueCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.DispatchDecisionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RescueCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DispatchDecisionLogs");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.HospitalCapabilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capability")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("HospitalCapabilities");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.HospitalCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BurnCapacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBurnLoad")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEmergencyLoad")
                        .HasColumnType("int");

                    b.Property<int>("CurrentIcuLoad")
                        .HasColumnType("int");

                    b.Property<int>("CurrentToxicologyLoad")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTraumaLoad")
                        .HasColumnType("int");

                    b.Property<int>("EmergencyCapacity")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("IcuCapacity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ToxicologyCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TraumaCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId")
                        .IsUnique();

                    b.ToTable("HospitalCapacities");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.RescueCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculatedSeverity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBreathingProblem")
                        .HasColumnType("bit");

                    b.Property<bool>("HasChemicalRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExplosionRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFire")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSevereBleeding")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTrappedVictim")
                        .HasColumnType("bit");

                    b.Property<int>("IncidentCategory")
                        .HasColumnType("int");

                    b.Property<int>("InjuryType")
                        .HasColumnType("int");

                    b.Property<bool>("IsUnconscious")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfPatients")
                        .HasColumnType("int");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RescueCases");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.RescueVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentCrewCount")
                        .HasColumnType("int");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<int>("MaxCrewCapacity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("RescueVehicles");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.ResponseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("EtaMinutes")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RescueVehicleId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsePlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RescueVehicleId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ResponsePlanId");

                    b.ToTable("ResponseAssignments");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.ResponsePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("EstimatedHospitalEtaMinutes")
                        .HasColumnType("float");

                    b.Property<double>("EstimatedSceneEtaMinutes")
                        .HasColumnType("float");

                    b.Property<string>("RejectedHospitalsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedVehiclesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredVehiclesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresHospital")
                        .HasColumnType("bit");

                    b.Property<int>("RescueCaseId")
                        .HasColumnType("int");

                    b.Property<bool>("SafetyValidationPassed")
                        .HasColumnType("bit");

                    b.Property<int?>("SelectedHospitalId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedVehiclesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("int");

                    b.Property<string>("ValidationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RescueCaseId")
                        .IsUnique();

                    b.HasIndex("SelectedHospitalId");

                    b.ToTable("ResponsePlans");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.SafetyValidationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckedRulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RescueCaseId")
                        .HasColumnType("int");

                    b.Property<bool>("ValidationPassed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SafetyValidationResults");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.SafetyViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RescueCaseId")
                        .HasColumnType("int");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViolationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SafetyViolations");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.VehicleEquipment", b =>
                {
                    b.Property<int>("RescueVehicleId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("RescueVehicleId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("VehicleEquipment");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.HospitalCapabilityEntity", b =>
                {
                    b.HasOne("RescueFlow.Web.Models.Entities.Hospital", "Hospital")
                        .WithMany("Capabilities")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.HospitalCapacity", b =>
                {
                    b.HasOne("RescueFlow.Web.Models.Entities.Hospital", "Hospital")
                        .WithOne("Capacity")
                        .HasForeignKey("RescueFlow.Web.Models.Entities.HospitalCapacity", "HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.RescueVehicle", b =>
                {
                    b.HasOne("RescueFlow.Web.Models.Entities.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.ResponseAssignment", b =>
                {
                    b.HasOne("RescueFlow.Web.Models.Entities.RescueVehicle", "RescueVehicle")
                        .WithMany()
                        .HasForeignKey("RescueVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RescueFlow.Web.Models.Entities.ResponsePlan", "ResponsePlan")
                        .WithMany("Assignments")
                        .HasForeignKey("ResponsePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueVehicle");

                    b.Navigation("ResponsePlan");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.ResponsePlan", b =>
                {
                    b.HasOne("RescueFlow.Web.Models.Entities.RescueCase", "RescueCase")
                        .WithOne("ResponsePlan")
                        .HasForeignKey("RescueFlow.Web.Models.Entities.ResponsePlan", "RescueCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RescueFlow.Web.Models.Entities.Hospital", "SelectedHospital")
                        .WithMany()
                        .HasForeignKey("SelectedHospitalId");

                    b.Navigation("RescueCase");

                    b.Navigation("SelectedHospital");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.VehicleEquipment", b =>
                {
                    b.HasOne("RescueFlow.Web.Models.Entities.Equipment", "Equipment")
                        .WithMany("VehicleEquipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RescueFlow.Web.Models.Entities.RescueVehicle", "RescueVehicle")
                        .WithMany("VehicleEquipment")
                        .HasForeignKey("RescueVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("RescueVehicle");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.Equipment", b =>
                {
                    b.Navigation("VehicleEquipment");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.Hospital", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.RescueCase", b =>
                {
                    b.Navigation("ResponsePlan");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.RescueVehicle", b =>
                {
                    b.Navigation("VehicleEquipment");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.ResponsePlan", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("RescueFlow.Web.Models.Entities.Station", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
